"use client";
import { Inter } from "next/font/google";
import Navbar from './navbar/page'
import Footer from './footer/footer'
import Section from "./first-screen/page";
import News from "./news/page";


const inter = Inter({ subsets: ["latin"] });

export const metadate = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">      
      <body>
        <Navbar/>
       
        {children} 
          <Footer/>
        </body>
        
    </html>
  );
}
